### ISSUE TITLE
incompatibility with excon 0.44.1

### ISSUE THREAD

**Issue by cydonian** [cloudbau/vagrant-openstack-plugin#105]
I'm using windows (8.1), cygwin (1.7.34), vagrant (1.7.2) , vagrant-openstack-plugin (0.11.1).
```
vagrant up --provider=openstack
```

gives me an error like this

```
$ vagrant up --provider=openstack
C:/Users/cydonian/.vagrant.d/gems/gems/excon-0.44.1/lib/excon/socket.rb:49:in `read_nonblock': A non-blocking socket operation could not be completed immediately. - read would block (Errno::EWOULDBLOCK) (Excon::Errors::SocketError)
        from C:/Users/cydonian/.vagrant.d/gems/gems/excon-0.44.1/lib/excon/socket.rb:49:in `readline'
        from C:/Users/cydonian/.vagrant.d/gems/gems/excon-0.44.1/lib/excon/response.rb:47:in `parse'
        from C:/Users/cydonian/.vagrant.d/gems/gems/excon-0.44.1/lib/excon/middlewares/response_parser.rb:6:in `response_call'
        from C:/Users/cydonian/.vagrant.d/gems/gems/excon-0.44.1/lib/excon/connection.rb:372:in `response'
        from C:/Users/cydonian/.vagrant.d/gems/gems/excon-0.44.1/lib/excon/connection.rb:236:in `request'
        from C:/Users/cydonian/.vagrant.d/gems/gems/fog-core-1.28.0/lib/fog/core/connection.rb:63:in `request'
        from C:/Users/cydonian/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/openstack/core.rb:202:in `retrieve_tokens_v2'
        from C:/Users/cydonian/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/openstack/core.rb:97:in `authenticate_v2'
        from C:/Users/cydonian/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/openstack/compute.rb:395:in `authenticate'
        from C:/Users/cydonian/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/openstack/compute.rb:320:in `initialize'
        from C:/Users/cydonian/.vagrant.d/gems/gems/fog-core-1.28.0/lib/fog/core/service.rb:115:in `new'
        from C:/Users/cydonian/.vagrant.d/gems/gems/fog-core-1.28.0/lib/fog/core/service.rb:115:in `new'
        from C:/Users/cydonian/.vagrant.d/gems/gems/fog-core-1.28.0/lib/fog/compute.rb:64:in `new'
        from C:/Users/cydonian/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.11.1/lib/vagrant-openstack-plugin/action/connect_openstack.rb:46:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
        from C:/Users/cydonian/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.11.1/lib/vagrant-openstack-plugin/provider.rb:33:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:480:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:141:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:75:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:75:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:614:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/up/command.rb:74:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:277:in `block (2 levels) in batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:275:in `tap'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:275:in `block in batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:274:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:274:in `batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/up/command.rb:58:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'

```

I was previously successfully using vagrant-openstack-plugin 0.9.0 probably installed around 24-Nov-2014, which appears to have installed excon 0.41.0. This was all working... until I upgraded vagrant-openstack-plugin to 0.11.1, which installed excon 0.44.1.

It appears that the use of `excon::socket.readline` somewhere causes the problem. This may be a bug in `excon::socket.readline` itself which calls `@socket.read_nonblock`. or it may be a problem with the way vagrant-openstack-plugin uses fog+excon.

I don't know enough about ruby, these gems or vagrant internals to actually do anything sensible (like pick different gems). So I hacked my excon to change this:

```
diff --git a/lib/excon/socket.rb b/lib/excon/socket.rb
index a0b0900..48f73a4 100644
--- a/lib/excon/socket.rb
+++ b/lib/excon/socket.rb
@@ -42,7 +42,11 @@ module Excon
       return legacy_readline if RUBY_VERSION.to_f <= 1.8_7
       begin
         buffer = ''
-        buffer << @socket.read_nonblock(1) while buffer[-1] != "\n"
+      if @nonblock
+        buffer << read_nonblock(1) while buffer[-1] != "\n"
+      else
+        buffer << read_block(1) while buffer[-1] != "\n"
+      end
         buffer
       rescue Errno::EAGAIN
         if timeout_reached('read')
```

It is not clear to me whether this is a bug in excon or an incompatibility with the way vagrant-openstack-plugin is using the fog+excon . 

Should vagrant-openstack-plugin be using fog+excon in such a way that it uses excon::socket.readline?

The nonblock stuff with readline appears to have been introduced in excon 0.44.1.

**Comment by cydonian** [comment]
see also https://github.com/excon/excon/issues/471

**Comment by cydonian** [comment]
fixed in excon 0.44.2

**Comment by ehaselwanter** [comment]
@cydonian so should we add a version constrain on the fog/excon dependency?

**Comment by cydonian** [comment]
not sure...

I did a `vagrant plugin update vagrant-openstack-plugin`, the result on my environment was an update to excon to 0.44.2. I don't know enough about managing gems to make that decision. I guess if you fork this gem change the Gemfile sources and the latest version of excon in your sources is < 0.44.2, then you will have the issue.

I suspect that you should, given that you have already have another constraint `fog '>=1.16.0'`... but what should the constraint be? It's broken only in excon 0.44.1 :-\ It works in 0.44.2 and I suspect it worked in 0.44.0.
