### ISSUE TITLE
openstack has no network service

### ISSUE THREAD

**Issue by lmorroni** [cloudbau/vagrant-openstack-plugin#115]
Hello,
We are trying to use the vagrant-openstack-plugin to create an instance.  When we run vagrant up, we get an error stating that "openstack has no network service".  Our OpenStack server is using a FlatDHCP network config.  We have been able to connect to the OpenStack server without issue using packer but things fail for vagrant.  One idea we had was that this was being caused because we do not have the Networking API Endpoint installed on our OpenStack Controller.  I'm not interested in adding that endpoint unless it's required.  Here is our Vagrant config:
```
  config.vm.provider :openstack do |os|
    os.server_name  = "My Server"
    os.username     = "fletch"
    os.api_key      = "XXXXXX"
    os.flavor       = /m1.medium/
    os.image        = "65def4c3-31f5-4653-a499-e9a854888b5e"
    os.endpoint     = "http://ctl1.XXXXX.com:5000/v2.0/tokens/"
    os.keypair_name = "vagrant-staging"
    os.ssh_username = "centos"
    os.tenant       = "admin"
    os.security_groups    = ['default']
    os.network            = "net-249"
  end
```
And here is the full error details:
```
home/centos/.vagrant.d/gems/gems/fog-core-1.31.1/lib/fog/network.rb:23:in `rescue in new': openstack has no network service (ArgumentError)
	from /home/centos/.vagrant.d/gems/gems/fog-core-1.31.1/lib/fog/network.rb:15:in `new'
	from /home/centos/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.11.1/lib/vagrant-openstack-plugin/action/connect_openstack.rb:50:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
...
```
Any help is greatly appreciated,
Larry

**Comment by lmorroni** [comment]
I wanted to also provide the output from `vagrant up --debug`
```
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-ce2384dbb59eccb457f96cacd5d6c96b
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000000021516c8>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000003671d50>
 INFO warden: Calling IN action: #<VagrantPlugins::OpenStack::Action::ConnectOpenStack:0x00000003671d00>
 INFO connect_openstack: Connecting to OpenStack...
DEBUG connect_openstack: API connection params: {:proxy=>nil, :ssl_verify_peer=>nil}
ERROR warden: Error occurred: openstack has no network service
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-ce2384dbb59eccb457f96cacd5d6c96b
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000000036c88a8>
/home/centos/.vagrant.d/gems/gems/fog-core-1.31.1/lib/fog/network.rb:23:in `rescue in new': openstack has no network service (ArgumentError)
```

**Comment by Chealion** [comment]
os.network is only required if you're using Neutron. If you're using nova-network you can omit it by setting `os.networks = []`. I think we need some more example Vagrantfiles posted.

**Comment by lmorroni** [comment]
That did the trick, thanks!

**Comment by ehaselwanter** [comment]
so I'll close this issue. re-open if needed
