### ISSUE TITLE
Bringing up a VM fails in Vagrant 1.5.4

### ISSUE THREAD

**Issue by stumped2** [cloudbau/vagrant-openstack-plugin#65]
I'm getting this stack trace when trying to bring up an openstack instance using the vagrant-openstack-plugin:

```bash
Bringing machine 'default' up with 'openstack' provider...
==> default: HandleBoxUrl middleware is deprecated. Use HandleBox instead.
==> default: This is a bug with the provider. Please contact the creator
==> default: of the provider you use to fix this.
==> default: Box 'dummy' could not be found. Attempting to find and install...
    default: Box Provider: openstack
    default: Box Version: >= 0
==> default: Adding box 'dummy' (v0) for provider: openstack
    default: Downloading: https://github.com/cloudbau/vagrant-openstack-plugin/raw/master/dummy.box
==> default: Successfully added box 'dummy' (v0) for 'openstack'!
==> default: Warning! The OpenStack provider doesn't support any of the Vagrant
==> default: high-level network configurations (`config.vm.network`). They
==> default: will be silently ignored.
==> default: Finding flavor for server...
==> default: Finding image for server...
/home/<user>/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.7.0/lib/vagrant-openstack-plugin/action/create_server.rb:56:in `call': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/warden.rb:34:in `call'
	from /home/<user>/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.7.0/lib/vagrant-openstack-plugin/action/connect_openstack.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/builtin/set_hostname.rb:16:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/warden.rb:34:in `call'
	from /home/<user>/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.7.0/lib/vagrant-openstack-plugin/action/warn_networks.rb:14:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/warden.rb:34:in `call'
	from /home/<user>/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.7.0/lib/vagrant-openstack-plugin/action/sync_folders.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/builtin/provision.rb:76:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/runner.rb:69:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/runner.rb:69:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/builtin/call.rb:51:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/builtin/handle_box_url.rb:9:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/runner.rb:69:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/action/runner.rb:69:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/machine.rb:157:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.5.4/lib/vagrant/batch_action.rb:72:in `block (2 levels) in run'
```

Other information: we use nova-network, so setting os.network or os.networks doesn't make any sense.

**Comment by ehaselwanter** [comment]
merged, re-open if still an issue
