### ISSUE TITLE
Error 404 when creating instances in HP Cloud

### ISSUE THREAD

**Issue by rcarrillocruz** [cloudbau/vagrant-openstack-plugin#83]
Since 9th September 2014, I'm unable to create instances in HP Cloud with Vagrant.

The Vagrantfile I use is very simple:

```
require 'vagrant-openstack-plugin'

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  # Make sure the private key from the key pair is provided
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider :openstack do |os|
    os.username     = "#{ENV['OS_USERNAME']}"          # e.g. "#{ENV['OS_USERNAME']}"
    os.api_key      = "#{ENV['OS_PASSWORD']}"           # e.g. "#{ENV['OS_PASSWORD']}"
    os.tenant       = "#{ENV['OS_TENANT_NAME']}" # optional
    os.endpoint     = "#{ENV['OS_AUTH_URL']}/tokens"      # e.g. "#{ENV['OS_AUTH_URL']}/tokens"
    os.flavor       = /small/                # Regex or String
    os.image        = /Ubuntu Server 14.04/                 # Regex or String
    os.keypair_name = "laptop"      # as stored in Nova
    os.ssh_username = "ubuntu"           # login for the VM

    os.networks           = [ "ricky-network" ]     # optional, overrides os.network
  end
end
```

This is the error I get:

```
ricky@ricky-HP-EliteBook-8570w:~/vagrants/hpcloud-test$ vagrant up
Bringing machine 'default' up with 'openstack' provider...
/home/ricky/.vagrant.d/gems/gems/excon-0.31.0/lib/excon/middlewares/expects.rb:6:in `response_call': Expected([200, 204, 300]) <=> Actual(404 Not Found) (Excon::Errors::NotFound)
  response => #<Excon::Response:0x007f052c861e28 @data={:body=>"{\"fault\":{\"faultstring\":\"Not Found\",\"detail\":{\"errorcode\":\"CLASSIFICATION_FAILURE\"}}}", :headers=>{"Content-Type"=>"application/>
        from /home/ricky/.vagrant.d/gems/gems/excon-0.31.0/lib/excon/middlewares/response_parser.rb:26:in `response_call'
        from /home/ricky/.vagrant.d/gems/gems/excon-0.31.0/lib/excon/connection.rb:398:in `response'
        from /home/ricky/.vagrant.d/gems/gems/excon-0.31.0/lib/excon/connection.rb:268:in `request'
        from /home/ricky/.vagrant.d/gems/gems/fog-1.19.0/lib/fog/core/connection.rb:56:in `request'
        from /home/ricky/.vagrant.d/gems/gems/fog-1.19.0/lib/fog/core/deprecated/connection.rb:20:in `request'
        from /home/ricky/.vagrant.d/gems/gems/fog-1.19.0/lib/fog/openstack.rb:216:in `get_supported_version'
        from /home/ricky/.vagrant.d/gems/gems/fog-1.19.0/lib/fog/openstack/network.rb:324:in `authenticate'
        from /home/ricky/.vagrant.d/gems/gems/fog-1.19.0/lib/fog/openstack/network.rb:238:in `initialize'
        from /home/ricky/.vagrant.d/gems/gems/fog-1.19.0/lib/fog/core/service.rb:68:in `new'
        from /home/ricky/.vagrant.d/gems/gems/fog-1.19.0/lib/fog/core/service.rb:68:in `new'
        from /home/ricky/.vagrant.d/gems/gems/fog-1.19.0/lib/fog/network.rb:17:in `new'
        from /home/ricky/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.8.0/lib/vagrant-openstack-plugin/action/connect_openstack.rb:50:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:196:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:173:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:403:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `action'
        from /home/ricky/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.8.0/lib/vagrant-openstack-plugin/provider.rb:33:in `state'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:432:in `state'
        from /home/ricky/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.8.0/lib/vagrant-openstack-plugin/action/is_created.rb:10:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/call.rb:43:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:196:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:173:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:434:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

Per the stack trace, the failure comes from a call hitting the Neutron endpoint (in my case it is https://region-b.geo-1.network.hpcloudsvc.com).
I exported EXCON_DEBUG=true to see the requests and responses and I see this:

```
excon.error  {:error=>#<Excon::Errors::NotFound: Expected([200, 204, 300]) <=> Actual(404 Not Found)
  response => #<Excon::Response:0x00000001ed7730 @data={:body=>"{\"fault\":{\"faultstring\":\"Not Found\",\"detail\":{\"errorcode\":\"CLASSIFICATION_FAILURE\"}}}", :headers=>{"Content-Type"=>"application/json", "Connection"=>"close", "Content-Length"=>"85"}, :status=>404, :remote_ip=>"206.164.176.32"}, @body="{\"fault\":{\"faultstring\":\"Not Found\",\"detail\":{\"errorcode\":\"CLASSIFICATION_FAILURE\"}}}", @headers={"Content-Type"=>"application/json", "Connection"=>"close", "Content-Length"=>"85"}, @status=404, @remote_ip="206.164.176.32">>}
excon.error  {:error=>#<Excon::Errors::NotFound: Expected([200, 204, 300]) <=> Actual(404 Not Found)
```

It seems the Neutron endpoint FQDN is resolved to the corresponding IP at some point and that makes the call to fail.
This is corroborated by the fact that I can curl to the Neutron endpoint just fine with DNS, whereas I get the same error returned by Vagrant if I curl the neutron endpoint via its IP:

```
ricky@ricky-HP-EliteBook-8570w:~/vagrants/hpcloud-test$ curl -X GET -H "X-Auth-Token: $TOKEN" https://region-b.geo-1.network.hpcloudsvc.com |python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   149  100   149    0     0    213      0 --:--:-- --:--:-- --:--:--   214
{
    "versions": [
        {
            "id": "v2.0",
            "links": [
                {
                    "href": "http://region-b.geo-1.network-internal.hpcloudsvc.com/v2.0",
                    "rel": "self"
                }
            ],
            "status": "CURRENT"
        }
    ]
}

```

```
ricky@ricky-HP-EliteBook-8570w:~/vagrants/hpcloud-test$ curl -k -X GET -H "X-Auth-Token: $TOKEN" https://206.164.176.32 |python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    85  100    85    0     0    192      0 --:--:-- --:--:-- --:--:--   192
{
    "fault": {
        "detail": {
            "errorcode": "CLASSIFICATION_FAILURE"
        },
        "faultstring": "Not Found"
    }
}
```

Any help is appreciated.

Regards

**Comment by ehaselwanter** [comment]
merged, re-open if still an issue
