### ISSUE TITLE
Destroying a deleted VM results in stack trace

### ISSUE THREAD

**Issue by cbaenziger** [cloudbau/vagrant-openstack-plugin#94]
If one does a `vagrant destroy -f && vagrant destroy -f` one ends up with the following stack trace:

````
ubuntu@clay-test:~/test$ vagrant destroy -f
==> claytest: Deleting server...
ubuntu@clay-test:~/test$ vagrant destroy -f
/home/ubuntu/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.9.0/lib/vagrant-openstack-plugin/action/delete_server.rb:15:in `call': undefined method `id' for nil:NilClass (NoMethodError)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
[...]
````

If one does this with vagrant on VirtualBox, one ends up with the much nicer:
````
cbaenzig@clay-desktop:/data/chef-bach$ vagrant destroy -f
[bootstrap] VM not created. Moving on...
````

**Comment by ehaselwanter** [comment]
merged, re-open if still an issue
